#!/bin/bash
install -v -d -m755 /usr/share/fonts                               &&
ln -svfn /usr/local/share/fonts/X11/OTF /usr/share/fonts/X11-OTF &&
ln -svfn /usr/local/share/fonts/X11/TTF /usr/share/fonts/X11-TTF
